<?php

namespace DevReymark\SourceEncryptor\Console;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;

class InstallCommand extends Command
{
    protected $signature = 'source:install';

    protected $description = 'Install the source encryptor and generate an encryption key';

    public function handle()
    {
        $this->info('Installing Source Encryptor...');

        $this->call('vendor:publish', [
            '--tag' => 'source-encryptor-config',
        ]);

        $this->generateKey();

        $this->info('Source Encryptor installed successfully.');
        
        return self::SUCCESS;
    }

    protected function generateKey()
    {
        $key = bin2hex(random_bytes(32));

        $envPath = base_path('.env');

        if (!File::exists($envPath)) {
            $this->warn('No .env file found. Please create one and add: SOURCE_ENCRYPTION_KEY=' . $key);
            return;
        }

        $env = File::get($envPath);

        if (str_contains($env, 'SOURCE_ENCRYPTION_KEY=')) {
            $this->warn('SOURCE_ENCRYPTION_KEY is already set in your .env file.');
            return;
        }

        $env .= "\n# Generated by Laravel Source Encryptor\nSOURCE_ENCRYPTION_KEY={$key}\n";

        File::put($envPath, $env);

        $this->info('Generated new SOURCE_ENCRYPTION_KEY and injected it into your .env file.');
    }
}
